Update sanitations.bal and operationId.bal for OData V4 Open API Specifications
ballerina-platform/module-ballerinax-sap.s4hana.delivery pull request #2
Opened 2024-06-26 10:53 UTC by Osara-B

## Purpose
Updating the sanitations.bal and operationId.bal to sanitize OData V4 Open API specifications. Adding a new example for ODATAV4 to the README.md.

## Checklist
- [ ] Updated sanitations.bal to correctly sanitize ODATAV4 Open API Specifications
- [ ] Updated operationId.bal to correctly sanitize ODATAV4 Open API Specifications
- [ ] Added a new example in README.md demonstrating the updated sanitization process for OData V4 Open API specifications.

2024-06-26 11:19 UTC, niveathika requested changes

2024-06-26 11:19 UTC, niveathika commented on docs/README.md
> +_Author_: @niveathika \
```suggestion
_Author_: @Osara-B  \  
_Reviewer_: @niveathika 
```

2024-06-26 11:19 UTC, niveathika commented on docs/README.md
> +_Updated_: 2024/05/21 \
Dates need to be updated

2024-06-26 11:19 UTC, niveathika commented on docs/sanitation/operationId.bal
> +// Copyright (c) 2024, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
Format the code. Same for all files

2024-06-26 11:39 UTC, niveathika commented on docs/sanitation/operationId.bal
> +    if (spec.x\-sap\-api\-type=="ODATAV4"){
Remove brackets in the condition

2024-06-27 06:17 UTC, Osara-B commented on docs/sanitation/operationId.bal
> +// Copyright (c) 2024, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
Changes done in the commit [Format code files and refresh timestamps and author details](https://github.com/ballerina-platform/module-ballerinax-sap.s4hana.delivery/pull/2/commits/d418fc6eb12fe437df297866a4746d8e2eb234c5)

> Format the code. Same for all files

2024-06-27 06:28 UTC, niveathika reviewed
@Osara-B's changes looks good to me. Lets wait for @osanda2024's fixes too and merge

2024-06-28 06:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ballerina-platform/module-ballerinax-sap.s4hana.delivery?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ballerina-platform/module-ballerinax-sap.s4hana.delivery?pullRequest=2) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Osara-B<br/>:x: osanda2024<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ballerina-platform/module-ballerinax-sap.s4hana.delivery?pullRequest=2) it.</sub>

2024-06-28 07:17 UTC, niveathika commented on docs/README.md
> +_Edition_: Swan Lake
```suggestion
_Author_: @Osara-B @osanda2024 \
_Reviewer_: @niveathika \
_Created_: 2024/06/27 \
_Updated_: 2024/06/28 \
_Edition_: Swan Lake  
```

2024-06-28 07:17 UTC, niveathika commented on docs/README.md
> +3. Add operation Ids. This is more user-friendly with SAP-specific scripts. The logic for parameter sanitization is
```suggestion
3. Improve response schema names by removing unnecessary prefixes and suffixes and renaming them to be more descriptive.
   `wrapper` -> `A_InspectionlotWrapper`
   `Collection of A_InspectionlotType` -> `CollectionOfA_Inspectionlot`

4. Add operation Ids. This is more user-friendly with SAP-specific scripts. The logic for parameter sanitization is
```

2024-06-28 07:17 UTC, niveathika commented on docs/sanitation/sanitations.bal
> +};
```suggestion
};

```

2024-06-28 07:21 UTC, niveathika approved these changes

2024-06-28 07:21 UTC, merged